server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: user-auth
          uri: http://user-service:8082
          predicates:
            - Path=/api/auth/**

        - id: user-info
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**

        - id: catalog-service
          uri: http://catalog-service:8083
          predicates:
            - Path=/api/catalog/**

        - id: order-service
          uri: http://order-service:8084
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
